# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade
        args: ["--py37-plus"]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6  # or specific git tag
  hooks:
    - id: forbid-binary
      #    - id: markdownlint # Configure in .mdlrc
      #      exclude: ^(CODE_OF_CONDUCT.md|README.md)$
    - id: shellcheck
      args: [
        "-e", "SC2128",  # allow non-index on array (yields first element)
        "-e", "SC2155",  # allow declare & assign
      ]

- repo: https://github.com/IamTheFij/docker-pre-commit
  rev: v2.1.0
  hooks:
        - id: docker-compose-check

- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args: [--in-place]

- repo: https://gitlab.com/iamlikeme/nbhooks
  rev: 1.0.0  # Set to the most recent version
  hooks:
  - id: nb-ensure-clean
    language_version: python3.6
    #args: [--meta, ExecuteTime]  # Optional blacklist of metadata keys (you can use regex)

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/tests/.*
